[build-system]
requires = ["uv_build>=0.10.7,<=0.12.1"]
build-backend = "uv_build"

[project]
name = "django-q2"
version = "1.10.0"
packages = [
    { include = "django_q" },
]
description = "A multiprocessing distributed task queue for Django"
authors = [
    { name = "Stan Triepels", email = "django-q2@stantriepels.com" },
    { name = "Ilan Steemers", email = "koed00@gmail.com" },
]
requires-python = ">=3.10,<4"
readme = "README.rst"
license = "MIT"
maintainers = [{ name = "Stan Triepels", email = "django-q2@stantriepels.com" }]
keywords = [
    "django",
    "distributed",
    "multiprocessing",
    "queue",
    "scheduler",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "Operating System :: POSIX",
    "Operating System :: MacOS",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: System :: Distributed Computing",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "django>=5.2",
    "django-picklefield>=3.1,<4",
    "importlib-metadata>=3.6 ; python_full_version < '3.10'",
]

[project.optional-dependencies]
testing = [
    "django-redis",
    "croniter",
    "hiredis",
    "psutil",
    "iron-mq",
    "boto3",
    "pymongo",
    "blessed",
    "redis",
    "setproctitle",
    "pytest",
    "pytest-django",
    "pytest-cov",
    "ruff",
]
croniter = ["croniter"]

[project.urls]
Homepage = "https://django-q2.readthedocs.org"
Repository = "https://github.com/GDay/django-q2"
Documentation = "https://django-q2.readthedocs.org"

[project.entry-points."djangoq.errorreporters"]
rollbar = "django_q_rollbar:Rollbar"
sentry = "django_q_sentry:Sentry"

[tool.uv.build-backend]
module-name = ["django_q"]
module-root = ""
source-include = ["CHANGELOG.md"]

[tool.isort]
profile = "black"
multi_line_output = 3
